# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4196f2d8b1462cce6ddddf4733e7adf38c79591254d497669732c199a94092bc309b69bd10c038943e3ac96df7d4e3e4a2eacf0a7c0b56422505873466d8db

test:
  secret_key_base: 0e7709f19b5134f3c5f23533d6c80c2163749bb3e4dcbecc93ddef12c97a3f8d4931628a3b67ab2ffb2fe2a5409e80d755116920ed185b36d4868a8cab79fe0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
